spring:
  application:
    name: Spring-Security-AuthN-Z
  datasource:
    url: jdbc:mysql://localhost:3306/customerdb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    database: mysql
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
